### ISSUE TITLE
FR: split the GixESQL (preprocessor and runtime library) from Gix

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#10]
If I understood the README correctly the roots of the ESQL implementation in Gix are to be found in https://github.com/opensourcecobol/Open-COBOL-ESQL .

It would be nice to:

* be able to check the differences and possibly pull some changes into ocesql
* be able to use GixESQL also outside of Gix
* be able to contribute to (and create issues for) GixESQL outside of Gix
* additional: if I understood that correctly GixESQL is possibly under a different license and its README + license headers could state that clearly

Therefore I suggest to move the components that handle preprocessing and the run-time-library parts to a separate repo (if it is based on ocesql it would be super cool to start with a fork of it, even if the first commit changes 80% of the code) and use it in Gix as it is done with the external libraries (and/or use it as a submodule, see #4), if both use too much components together then it could be possible to create a third repo gix-common

**Comment by mridoni** [comment]
Moving GixSQL to a separate repository presents the same problem as in #11: good idea but first I have to change my workflow, it will be happening but I cannot currently give an ETA because I'd like to address other things first (currently lacking features and general stability/usability). 

With regard to OceSQL: it is very complicated and not really possible to simply merge code between the two, simply because some parts (parser and scanner) have been almost completely rewritten in C++ (instead of C), others (the main library) have been extended and refactored so much  that they have little in common anymore. Obviously, given the license GixSQL comes under, should anyone need/want to do it, is free to do so.

BTW: GixSQL is already usable outside of Gix (it still needs Qt), I just have to write the documentation for it: the core is in libgixpp, which is built as a static library. Have a look at the gixpp tool in the source, that works as a driver for the library.

**Comment by GitMensch** [comment]
Thank you for taking the time to answer. With that additional information I'd say an "official fork" is not reasonable in this case.
That's obviously completely different with #11.

> Moving GixSQL to a separate repository presents the same problem as in #11: good idea but first I have to change my workflow, it will be happening but I cannot currently give an ETA because I'd like to address other things first

Can I suggest to keep this open and add this and #11 to a common mile stone without any ETA and possibly an additional new issue about the internal workflow change?

**Comment by mridoni** [comment]
Sorry, but for now this is not an option for me. As I said, I am not going to change my workflow for the time being and I am not creating separate repositories that would become an additional burden to manage. 

Depending on how Gix-IDE as a whole will evolve, this might change, but given that this is done in my spare time, I cannot make any promises or guarantee that I will stick to any timeline. 

I understand that for someone the centerpiece might be just GixSQL, but for me it is Gix-IDE as a whole, and since I want to improve it and make it more reliable, I need to focus my efforts on that; so I am not making any choice that would slow down or hinder my ability to work on the kind of work I want to do.

Since I also understand that there might be a need for a separate install of GixSQL, in the next release, as I said, I will publish binary packages and build instructions only for it, but all starting from the same repository.

**Comment by GitMensch** [comment]
Just to leave the note here: this was now done with 1.0.13 where gixsql was moved out to https://github.com/mridoni/gixsql; also moved were the open issues related to gixsql.

I think it _may_ be reasonable to also move some of the fixed ones (but not necessary), which would be #30 (actually a question), #33, #39, #50, #53, #55, #58, #62, #73, #93.
