### ISSUE TITLE
Permit adjustments to the runtime environment 

### ISSUE THREAD

**Issue by jmmittan** [mridoni/gix#101]
Gix does provide good support for programs that use the screen section,  including support for function keys. But support for mouse interactions with the screen is currently unsupported. GnuCOBOL has mouse support turned off by default.  An environment variable must be adjusted at runtime to turn it on, and the Gix IDE currently lacks a way to do this. There are several other runtime environment variables that should be also be supported.

**Comment by GitMensch** [comment]
So is your suggestion to have a dialog with all settings that `cobcrun --runtime-config` shows (details are found in config/runtime.cfg or the part that is generated from this in the gnucobol manual) - or simply a way to configure, per project, "environment variables" - allowing you to set them on your own?

**Comment by mridoni** [comment]
> There are several other runtime environment variables that should be also be supported.

You are right: there is not a specific setting in the Properties window for a project, but for now you can manually set environment variables in “Run/Debug environment”, in the same window.

Obviously I am open to any suggestion to improve this, both for compile-time and runtime parameter, I guess the one made above by @GitMensch is a good starting point, also because many things (e.g. compile flags or dialects) depend by the version of GnuCOBOL being used.

**Comment by jmmittan** [comment]
I must admit that I did not see the Run/Debug environment option as being applicable to my situation.  Just tried it, and it works.  Let's close this issue. A similar facility for compiler options (issue 88) would be very nice. Or am I overlooking something else?
