### ISSUE TITLE
Request for carification: What compiler binaries are contained in the releases?

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gix#118]
We have "installer" and "installer-no-compilers", but what compiler binaries are actually included in the first version?
Note: a reasonable version info can be seen with `cobcrun -vV | tail -n2`.

I guess it would be reasonable to adjust the general note at https://github.com/mridoni/gix#compiler-packages a bit (maybe add the featureset and note if x86 and x64 contain the same compilers [for VC you likely would want to note that it needs to be installed separately, if that's not part of the installer]) and have a note in each release which Win32 compilers are included using the version output as mentioned above.

**Comment by mridoni** [comment]
This is actually undergoing a massive overhaul: I am moving the build/packaging process to GitHub and developing the actions and workflows to handle it (obviously this also applies to GixSQL). Part of this work consists in developing a few workflows that automatically build GnuCOBOL compiler binaries (for Windows and Linux). These will be used to generate the compilers to be added to the Gix-IDE install package, but of course will be available for anyone to use (and, quite obviously, for the GnuCOBOL project itself). 

Having had little time in these weeks (and since I will be leaving for a vacation in a few days) I decided to finally tackle this work, that can be managed in a "bits-and pieces" style (basically: when I have the time) and will help to give more structure and to better manage the project(s) as a whole.

When completed, the workflows will be made public under the usual GPL+LGPL license. For now, and until I am satisfied with the results, I am working in a private repository (and using a self-hosted runner, that makes the seemingly infinite "edit-commit-run-check log-fix-repeat" cycle more bearable).

**Comment by GitMensch** [comment]
Just some notes to possibly help with that work:

* the most up-to-date GitHub workflows I'm available on are at https://github.com/OCamlPro/gnucobol/tree/gcos4gnucobol-3.x/.github/workflows
* the appveyor definition for building with VC is at https://github.com/OCamlPro/gnucobol/issues/48 (I could provide the other workflows if that helps [building on several versions of Ubuntu and MacOS, MinGW, Cygwin, Cygwin64])
* the MSYS2 definition may be used to build there with `pacman`, possibly before using the `make distbindir`, see https://sourceforge.net/p/gnucobol/discussion/help/thread/a077f88fa7/?limit=50#ff3f and https://sourceforge.net/p/gnucobol/discussion/help/thread/06898ecf60/?limit=50#773a/c46e/67a1
* the binary distribution package after building are available by
    * `make distbin`  (common GNU/Linux, suffix with `-xz` or others to create an archive, or `make distbindir` for the folder only)
    * `make distmingwdir` (creates a folder you may want to add to before packaging, similar to `make distbindir` above, but with a created set_env.cmd and conversion to DOS EOL markers)
    * `build_windows\makedist.cmd` to create a package for use with VC (commonly compiled with msbuild as seen in the appveyor definition referenced above)

**Comment by mridoni** [comment]
> Just some notes to possibly help with that work:

Ok, thanks, I am already the OCamlPro repository for the GnuCOBOL sources, and the MSVC workflow is almost there (it basically works, but there are still some wrinkles to be ironed). I will look into it for the MinGW(32/64) build, that is currently a re-pack of a minimal MSYS2 install tree with the GnuCOBOL packages installed. It works, obviously, but it is huge and I would like to slim it down at least a little

**Comment by GitMensch** [comment]
> I will look into it for the MinGW(32/64) build, that is currently a re-pack of a minimal MSYS2 install tree with the GnuCOBOL packages installed. It works, obviously, but it is huge and I would like to slim it down at least a little

I guess you want something like the following (in MSYS2 with whatever state):

```sh
mkdir -p $HOME/gconly
pacman --noconfirm --root=$HOME/gconly --dbpath=$HOME/gconly -Sy mingw-w64-x86_64-gnucobol mingw-w64-x86_64-gnucobol
```

and then use the created folders `$HOME/gconly/mingw32` and `$HOME/gconly/mingw64` (500/600 MB); if you want to test a bit around you should be able to slim that down a lot by removing unnecessary files under "include", "share" and "lib".

... and if you want GDB debugging experience (which in your case is likely not the case) add packages `mingw-w64-x86_64-gdb-multiarch mingw-w64-x86_64-python-pygments`  [no need to install i686, as the x64_64 can debug this, too; maybe the GDB part is best kept as separate = 3rd package])

**Comment by mridoni** [comment]
> I guess you want something like the following (in MSYS2 with whatever state):

Your suggestion worked as expected, thanks again.

**Comment by GitMensch** [comment]
Nearly done with the new distribution, as the only missing piece is the "detail version" as seen with `cobcrun -vV` I'm closing this in favor of #123.
