### ISSUE TITLE
Is it possible to compile on termux proot Ubuntu 22 on aarch64 (arm64) ?

### ISSUE THREAD

**Issue by jean306** [mridoni/gix#139]
Hello.
The question is in thé title ....
Or is there a project for thé architecture Arm64 with Android and termux ?
Your job is awesome ...
Thanks

**Comment by GitMensch** [comment]
While GnuCOBOL handles any architecture and all modern and a bunch of old compilers (as far as known) I _think_ that the GUI of Gix IDE and possibly also the Gix Debugger won't handle other architectures than x86 and x86_64 - but I don't know.

To compile using GnuCOBOL on aarch64: either install GnuCOBOL with `apt` or build it on your own starting from a tarball.
Note: If the underlying compiler is clang, then you likely have to add `CFLAGS=-Wno-deprecated-non-prototype` on its configure line.
If you have questions about building GnuCOBOL, please use the GC discussion boards https://sourceforge.net/p/gnucobol/discussion/help/ instead of this issue tracker.

**Comment by jean306** [comment]
Thanks for thé response.
The GnuCobol is ok on termux proot Ubuntu 22.
The question is for this Ide ... and I know that the response is not easy...

**Comment by jean306** [comment]
Another possibility is to install wine on Ubuntu 22 (termux and Android) and then put the version x86 or x64 of gix-ide.
For instance, I only begin to install wine ... it's not fonctionnal....

**Comment by mridoni** [comment]
It depends on several things: first of all the availability of a compatibile version of Qt: 5.14.2 is the version currently being used, but other versions might work (did not test it at all with 6.x).

The debugger is of course completely architecture and OS-specific, so it might even compile witha few modifications, but given the way it is implemented (setting trap instructions at runtime) it will surely fail to work.

**Comment by jean306** [comment]
Thanks for the response. If I can go further, I sens a new message. Have a good day.
